PETNET/PETNET/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PETNET.Models;

namespace PETNET.Controllers
{
    public class AdminCategoryController : Controller
    {
        private PetnetDB db = new PetnetDB();

        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategorieID,CategorieName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategorieID,CategorieName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

  
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PETNET/PETNET/Views/AdminCategory/Create.cshtml
@model PETNET.Models.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.ekle</h2>


@using (Html.BeginForm("Create", "AdminCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KATEGORİ</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategorieName,dil.HomeTexts.ekle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategorieName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategorieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="EKLE" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(dil.HomeTexts.geri, "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PETNET/PETNET/Views/AdminCategory/Delete.cshtml
@model PETNET.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.sil</h2>

<h3>@dil.HomeTexts.siluyar</h3>
<div>
    <h4>@dil.HomeTexts.kategoriler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink(dil.HomeTexts.geri, "Index")
        </div>
    }
</div>

PETNET/PETNET/Views/AdminCategory/Details.cshtml
@model PETNET.Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.detaylar</h2>

<div>
    <h4>@dil.HomeTexts.kategoriler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(dil.HomeTexts.duzenle, "Edit", new { id = Model.CategorieID }) |
    @Html.ActionLink(dil.HomeTexts.geri, "Index")
</p>

PETNET/PETNET/Views/AdminCategory/Edit.cshtml
@model PETNET.Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.duzenle</h2>


@using (Html.BeginForm("Edit", "AdminCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@dil.HomeTexts.kategoriler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategorieID)

        <div class="form-group">
            @Html.LabelFor(model => model.CategorieName,dil.HomeTexts.kategoriler, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategorieName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategorieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@dil.HomeTexts.kaydet class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(dil.HomeTexts.geri, "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PETNET/PETNET/Views/AdminCategory/Index.cshtml
@model IEnumerable<PETNET.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.kategoriler</h2>

<p>
    @Html.ActionLink(dil.HomeTexts.ekle, "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategorieName)
        </td>
        <td>
            @Html.ActionLink(dil.HomeTexts.duzenle, "Edit", new { id=item.CategorieID }) |
            @Html.ActionLink(dil.HomeTexts.detaylar, "Details", new { id=item.CategorieID }) |
            @Html.ActionLink(dil.HomeTexts.sil, "Delete", new { id=item.CategorieID })
        </td>
    </tr>
}

</table>