PETNET/PETNET/Controllers/AdminBlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PETNET.Models;

namespace PETNET.Controllers
{
    public class AdminBlogController : Controller
    {
       PetnetDB db = new PetnetDB();

        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

    
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        
        public ActionResult Create()
        {
            ViewBag.CategorieID = new SelectList(db.Categories, "CategorieID", "CategorieName");
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Blog blog,HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    WebImage img=new WebImage(Photo.InputStream);
                    FileInfo photoInfo=new FileInfo(Photo.FileName);

                    string newPhoto = Guid.NewGuid().ToString() + photoInfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/BlogsPhoto/" + newPhoto);
                    blog.Photo = "/Uploads/BlogsPhoto/" + newPhoto;
                    
                }
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
          
            return View(blog);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogID,Title,Text,Photo,Date,UserID,ReadingCount,CategorieID")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PETNET/PETNET/Views/AdminBlog/Create.cshtml
@model PETNET.Models.Blog

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.ekle</h2>


@using (Html.BeginForm("Create","AdminBlog",FormMethod.Post,new{enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@dil.HomeTexts.eklenecekblog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.UserID, @dil.HomeTexts.uye, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList( "UserID",null, htmlAttributes: new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategorieID, dil.HomeTexts.kategoriler, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList( "CategorieID",null, htmlAttributes: new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.CategorieID, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.LabelFor(model => model.Title, dil.HomeTexts.baslik, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, dil.HomeTexts.icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, dil.HomeTexts.fotograf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <input type="file" name="Photo" id="Photo" accept=".jpeg,.JPEG,.Jpeg,.gif,.png" class = "form-control"/>
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, dil.HomeTexts.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" , @type="date" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="EKLE" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(dil.HomeTexts.geri, "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PETNET/PETNET/Views/AdminBlog/Delete.cshtml
@model PETNET.Models.Blog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.sil</h2>

<h5>@dil.HomeTexts.siluyar</h5>
<div>
    <h4>BLOG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(dil.HomeTexts.uye)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieID)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.fotograf)
        </dt>

        <dd>
            <img width="75" src="@Model.Photo" />
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

       </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="SİL" class="btn btn-default" /> |
            @Html.ActionLink(dil.HomeTexts.geri, "Index")
        </div>
    }
</div>

PETNET/PETNET/Views/AdminBlog/Details.cshtml
@model PETNET.Models.Blog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>BLOG</h2>

<div>
    <h4>@dil.HomeTexts.detaylar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(dil.HomeTexts.uye)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategorieID)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.fotograf)
        </dt>

        <dd>
            <img width="75" src="@Model.Photo" />
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(dil.HomeTexts.duzenle, "Edit", new { id = Model.BlogID }) |
    @Html.ActionLink(dil.HomeTexts.geri, "Index")
</p>

PETNET/PETNET/Views/AdminBlog/Edit.cshtml
@model PETNET.Models.Blog

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.duzenle</h2>


@using (Html.BeginForm("Edit", "AdminBlog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>@dil.HomeTexts.duzenlenecekblog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.BlogID)

    <div class="form-group">
        @Html.LabelFor(model => model.UserID, dil.HomeTexts.uye, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CategorieID, dil.HomeTexts.kategoriler, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CategorieID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CategorieID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Title, dil.HomeTexts.baslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, dil.HomeTexts.icerik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Photo,dil.HomeTexts.eskifotograf, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img width="75" src="@Model.Photo"/>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Photo, dil.HomeTexts.fotograf, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Photo" id="Photo" accept=".jpeg,.JPEG,.Jpeg,.gif,.png" class = "form-control"/>
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date,dil.HomeTexts.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value=@dil.HomeTexts.kaydet class="btn btn-default" />
        </div>
    </div>
</div>
}

    <div>
        @Html.ActionLink(dil.HomeTexts.geri, "Index")
    </div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PETNET/PETNET/Views/AdminBlog/Index.cshtml
@model IEnumerable<PETNET.Models.Blog>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>BLOGLAR</h2>

<p>
    @Html.ActionLink(dil.HomeTexts.ekle, "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName(@dil.HomeTexts.uye)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.kategoriler)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.baslik)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.icerik)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.fotograf)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.tarih)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategorieID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
          <img width="75" src="@item.Photo"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
       <td>
            @Html.ActionLink(dil.HomeTexts.duzenle, "Edit", new {id = item.BlogID}) |
            @Html.ActionLink(dil.HomeTexts.detaylar, "Details", new {id = item.BlogID}) |
            @Html.ActionLink(dil.HomeTexts.sil, "Delete", new {id = item.BlogID})
        </td>
    </tr>
}

</table>