PETNET/PETNET/Controllers/AdminAnimalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PETNET.Models;

namespace PETNET.Controllers
{
    public class AdminAnimalController : Controller
    {
       PetnetDB db = new PetnetDB();
        
        public ActionResult Index()
        {
            var animals = db.Animals.Include(a => a.User);
            return View(animals.ToList());
        }

       public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Animal animal,HttpPostedFileBase Photo)
        {
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");
            try
            {
                if (ModelState.IsValid)
                {
                    if (Photo != null)
                    {
                        WebImage img = new WebImage(Photo.InputStream);
                        FileInfo photoInfo = new FileInfo(Photo.FileName);

                        string newPhoto = Guid.NewGuid().ToString() + photoInfo.Extension;
                        img.Resize(800, 350);
                        img.Save("~/Uploads/AnimalsPhoto/" + newPhoto);
                        animal.Photo = "/Uploads/AnimalsPhoto/" + newPhoto;


                    }
                    db.Animals.Add(animal);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                db.SaveChanges();
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }
           

            return View(animal);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", animal.UserID);
            return View(animal);
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AnimalID,UserID,Name,Gender,Type,Kind,Photo")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(animal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", animal.UserID);
            return View(animal);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Animal animal = db.Animals.Find(id);
            db.Animals.Remove(animal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PETNET/PETNET/Views/AdminAnimal/Create.cshtml
@model PETNET.Models.Animal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.ekle</h2>


@using (Html.BeginForm("Create", "AdminAnimal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@dil.HomeTexts.sahiphayvan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, dil.HomeTexts.ekleyenkullanici, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, @dil.HomeTexts.ismi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, dil.HomeTexts.cinsiyeti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, dil.HomeTexts.turu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kind, dil.HomeTexts.cinsi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, dil.HomeTexts.fotograf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Photo" id="Photo" accept=".jpeg,.JPEG,.Jpeg,.gif,.png" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@dil.HomeTexts.ekle class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(dil.HomeTexts.geri, "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PETNET/PETNET/Views/AdminAnimal/Delete.cshtml
@model PETNET.Models.Animal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.sil</h2>

<h5>@dil.HomeTexts.siluyar</h5>
<div>
    <h4>@dil.HomeTexts.sahiphayvan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(@dil.HomeTexts.ekleyenkullanici)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayName(@dil.HomeTexts.ismi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayName(@dil.HomeTexts.cinsiyeti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayName(@dil.HomeTexts.turu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayName(@dil.HomeTexts.cinsi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kind)
        </dd>

        <dt>
            @Html.DisplayName(@dil.HomeTexts.fotograf)
        </dt>

        <dd>
            <img width="75" src="@Model.Photo" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="SİL" class="btn btn-default" /> |
            @Html.ActionLink(@dil.HomeTexts.geri, "Index")
        </div>
    }
</div>

PETNET/PETNET/Views/AdminAnimal/Details.cshtml
@model PETNET.Models.Animal

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.detaylar</h2>

<div>
    <h4>@dil.HomeTexts.sahiphayvan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(dil.HomeTexts.ekleyenkullanici)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.ismi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.cinsiyeti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.turu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.cinsi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kind)
        </dd>

        <dt>
            @Html.DisplayName(dil.HomeTexts.fotograf)
        </dt>

        <dd>
            <img width="75" src="@Model.Photo" />
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink(@dil.HomeTexts.geri, "Index")
</p>

PETNET/PETNET/Views/AdminAnimal/Index.cshtml
@model IEnumerable<PETNET.Models.Animal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>@dil.HomeTexts.sahiplendirelecek</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName(dil.HomeTexts.ekleyenkullanici)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.ismi)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.cinsiyeti)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.turu)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.cinsi)
        </th>
        <th>
            @Html.DisplayName(dil.HomeTexts.fotograf)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kind)
        </td>
        <td>
            <img width="75" src="@item.Photo"/>
        </td>
        <td>
            @Html.ActionLink(@dil.HomeTexts.detaylar, "Details", new { id=item.AnimalID }) |
            @Html.ActionLink(@dil.HomeTexts.sil, "Delete", new { id=item.AnimalID })
        </td>
    </tr>
}

</table>